## template: jinja
{% set user = user or "mike" %}
{% set ssh_key = ssh_key or "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIsrQEHKvwPZI8lOBF1j7t9pMUW28pRAZ914BjTnAwW7 mike@kwyk.net" %}

#cloud-config
users:
  - name: {{ user }}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - {{ ssh_key }}

package_update: true
package_upgrade: true
packages:
  - openssh-server
  - avahi-daemon
  - curl
  - wget

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - usermod -aG docker {{ user }}

# launch: incus launch images:ubuntu/24.04/cloud $HOST -p bridged --config=cloud-init.user-data="$(cat docker-ud.yml)"