## template: jinja
{% set user = user or "mike" %}
{% set ssh_key = ssh_key or "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIsrQEHKvwPZI8lOBF1j7t9pMUW28pRAZ914BjTnAwW7 mike@kwyk.net" %}

#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - tree
  - avahi-daemon
  - openssh-server
  - wget
  - git
  - build-essential
  - software-properties-common
  - ca-certificates
  - gnupg
  - lsb-release
  - nano
  - direnv
  - python3
  - python3-pip
  - python3-venv
  - tmux
  - jq

users:
  - name: {{ user }}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - {{ ssh_key }}

runcmd:
  - curl -fsSL https://gist.github.com/mikestankavich/137742bceb0215265103d947d25f9fa9/raw/bootstrap-claude-code-sandbox.sh | bash -s -- {{ user }}
